// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zRd1iqSD7m_Va7WOlKPiE1wT5baSN-k',
    appId: '1:881072123404:web:4d5efd6b71648c70be8829',
    messagingSenderId: '881072123404',
    projectId: 'uniflow-f4375',
    authDomain: 'uniflow-f4375.firebaseapp.com',
    storageBucket: 'uniflow-f4375.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQw-o53VcDj5Wpxh83YtCejOWjYVI5_KA',
    appId: '1:881072123404:android:3ed2dc3f206a5155be8829',
    messagingSenderId: '881072123404',
    projectId: 'uniflow-f4375',
    storageBucket: 'uniflow-f4375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsp6m_Tr_kL-g3rT8aNvJBLO5jH24JCsY',
    appId: '1:881072123404:ios:b26a8c276eb600e0be8829',
    messagingSenderId: '881072123404',
    projectId: 'uniflow-f4375',
    storageBucket: 'uniflow-f4375.firebasestorage.app',
    iosBundleId: 'com.aamir.uniflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsp6m_Tr_kL-g3rT8aNvJBLO5jH24JCsY',
    appId: '1:881072123404:ios:b26a8c276eb600e0be8829',
    messagingSenderId: '881072123404',
    projectId: 'uniflow-f4375',
    storageBucket: 'uniflow-f4375.firebasestorage.app',
    iosBundleId: 'com.aamir.uniflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5zRd1iqSD7m_Va7WOlKPiE1wT5baSN-k',
    appId: '1:881072123404:web:f2c31e643813aa94be8829',
    messagingSenderId: '881072123404',
    projectId: 'uniflow-f4375',
    authDomain: 'uniflow-f4375.firebaseapp.com',
    storageBucket: 'uniflow-f4375.firebasestorage.app',
  );
}
